### PR TITLE
Fix embedded binary parameter loading

### LINKED ISSUE #42: Overdetecting ERROR_HALL_ENC on binary embedded parameter mode
initialization order problem?

### PR DESCRIPTION
**Pull request by at-wat**
fix #42

### CODE REVIEW

File: tfrog-motordriver/main.c [hunk 1]
```diff
@@ -585,30 +583,46 @@ int main()
...
+    EEPROM_Read(TFROG_EEPROM_ROBOTPARAM_ADDR + 0x200, &motor_param[1], sizeof(MotorParam));
+
+    if (motor_param[0].enc_rev_raw / motor_param[0].enc_denominator != motor_param[0].enc_rev ||
+        motor_param[1].enc_rev_raw / motor_param[1].enc_denominator != motor_param[1].enc_rev)
+    {
+      TRACE_ERROR("Embedded parameter has inconsistency\n\r");
+      printf("enc_rev: %d, %d\n\r", motor_param[0].enc_rev, motor_param[1].enc_rev);
+      printf("enc_denominator: %d, %d\n\r", motor_param[0].enc_denominator, motor_param[1].enc_denominator);
+      printf("enc_rev_raw: %d, %d\n\r", motor_param[0].enc_rev_raw, motor_param[1].enc_rev_raw);
+      AT91C_BASE_RSTC->RSTC_RCR = 0xA5000000 | AT91C_RSTC_EXTRST | AT91C_RSTC_PROCRST | AT91C_RSTC_PERRST;
```
Comment (at-wat) [inline tfrog-motordriver/main.c]: need parameter version check. otherwise, endless reset loop occurs.

**Comment by at-wat** [comment]
Before adding a new field.
```
0177AA003500010000003001756E6B6E6F776E00000000000000000000000000
000000000000000000000000B0040A000100000000000000FFFF
```

After adding the char field at the end (deafult value 0xAA).
```
0177AA003600010000003001756E6B6E6F776E00000000000000000000000000
000000000000000000000000B0040A000100000000AA0000FFFF
```

Size is calculated correctly even if the size() is not changed due to the trailing padding.

```
-- Locomotion Board 1.5 --
-- T-frog Motor Driver rev.5
-- Compiled: Mar 29 2019 15:43:56 --
User Reset. NRST pin detected low.
SRAM init
FPGA ID: 1a0
FPGA test
ADC init
Migrating EEPROM data  # <- migrated as expected
Velocity Control init
PWM control init
Watchdog init
Start ticker
RS485 init
Board version: R6, R6A
Entering main control loop
```

**Comment by at-wat** [comment]
@DaikiMaekawa please take a look. sorry, this will make conflicts with your PR.

**Review by DaikiMaekawa — APPROVED** [review]
