### PR TITLE
Fix initial state

### LINKED ISSUE #45: Investigate initial state and enable soft start
- check and fix internal value initialization
- enable soft start at control init

### PR DESCRIPTION
**Pull request by at-wat**
fix #45

### CODE REVIEW

File: tfrog-motordriver/controlVelocity.c [hunk 1]
```diff
@@ -362,6 +369,7 @@ void controlVelocity_init()
   driver_param.admask = 0;
   driver_param.io_mask[0] = 0;
   driver_param.io_mask[1] = 0;
+  driver_param.control_cycle = 1;
```
Comment (at-wat) [inline tfrog-motordriver/controlVelocity.c:372]: Initial value at boot time was random.
It could cause very long interval of velocity calculation; count/interval value was very large if motor is rotating at start time.
